// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.Backend.Data;

#nullable disable

namespace eCommerce.Backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eCommerce.Backend.Models.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Appconfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "HomeTitle",
                            Value = "This is home page of eCommerceWebsite"
                        },
                        new
                        {
                            Key = "HomeKeyword",
                            Value = "This is keyword of eCommerceWebsite"
                        },
                        new
                        {
                            Key = "HomeDescription",
                            Value = "This is description of eCommerceWebsite"
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("725efe2e-a534-40c4-ab0d-20c947e6c0eb"),
                            ConcurrencyStamp = "d379edef-0a85-48c9-9c1d-99d4eddf540b",
                            Description = "Administrator role",
                            Name = "admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf517a65-75d0-480c-9566-601b1e607d25"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c063d31a-c81f-4626-8d4c-3fb21b7d4631",
                            Dob = new DateTime(2022, 3, 3, 21, 47, 18, 263, DateTimeKind.Local).AddTicks(1170),
                            Email = "tranhatuankiet1709@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Tu",
                            LastName = "Ki",
                            LockoutEnabled = false,
                            NormalizedEmail = "tranhatuankiet1709@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEDUwHKTufxBPeXT50w5jzz+xI2JfKCuGl5OzWfK6MfubC2cGccz1IsNssqQWcnW1ow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsShowOnHome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeoAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6940),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Andora",
                            SeoAlias = "Andora",
                            SeoDescription = "Andora's accessories",
                            SeoTitle = "Andora's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6960),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Apple",
                            SeoAlias = "Apple",
                            SeoDescription = "Apple's accessories",
                            SeoTitle = "Apple's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6960),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Anker",
                            SeoAlias = "Anker",
                            SeoDescription = "Anker's accessories",
                            SeoTitle = "Anker's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6960),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Baseus",
                            SeoAlias = "Baseus",
                            SeoDescription = "Baseus's accessories",
                            SeoTitle = "Baseus's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6970),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Hyper",
                            SeoAlias = "Hyper",
                            SeoDescription = "Hyper's accessories",
                            SeoTitle = "Hyper's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6970),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Filco",
                            SeoAlias = "Filco",
                            SeoDescription = "Filco's accessories",
                            SeoTitle = "Filco's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6970),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "JCPAL",
                            SeoAlias = "JCPAL",
                            SeoDescription = "JCPAL's accessories",
                            SeoTitle = "JCPAL's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6970),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Keychrone",
                            SeoAlias = "Keychrone",
                            SeoDescription = "Keychrone's accessories",
                            SeoTitle = "Keychrone's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6970),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Lofree",
                            SeoAlias = "Lofree",
                            SeoDescription = "Lofree's accessories",
                            SeoTitle = "Lofree's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6970),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Logitech",
                            SeoAlias = "Logitech",
                            SeoDescription = "Logitech's accessories",
                            SeoTitle = "Logitech's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6970),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Mocoll",
                            SeoAlias = "Mocoll",
                            SeoDescription = "Mocoll's accessories",
                            SeoTitle = "Mocoll's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6980),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Philips",
                            SeoAlias = "Philips",
                            SeoDescription = "Philips's accessories",
                            SeoTitle = "Philips's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6980),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "Tucano",
                            SeoAlias = "Tucano",
                            SeoDescription = "Tucano's accessories",
                            SeoTitle = "Tucano's accessories",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(6980),
                            Image = "",
                            IsShowOnHome = true,
                            Name = "WIWU",
                            SeoAlias = "WIWU",
                            SeoDescription = "WIWU's accessories",
                            SeoTitle = "WIWU's accessories",
                            SortOrder = 0,
                            Status = 1
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsShowOnHome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("SeoAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7000),
                            IsShowOnHome = true,
                            Name = "Macbook's Accessories",
                            SeoAlias = "Macbook-accessories",
                            SeoDescription = "The accessories products for Macbook",
                            SeoTitle = "The accessories products for Macbook",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7000),
                            IsShowOnHome = true,
                            Name = "Iphone's Accessories",
                            SeoAlias = "Iphone-accessories",
                            SeoDescription = "The accessories product for Iphone",
                            SeoTitle = "The accessories product for Iphone",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7000),
                            IsShowOnHome = true,
                            Name = "Ipad's Accessories",
                            SeoAlias = "Ipad-accessories",
                            SeoDescription = "The accessories product for Ipad",
                            SeoTitle = "The accessories product for Ipad",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7000),
                            IsShowOnHome = true,
                            Name = "Mechanical",
                            SeoAlias = "Mechanical",
                            SeoDescription = "The Mechanical products for Apple devices",
                            SeoTitle = "The Mechanical products for Apple devices",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7010),
                            IsShowOnHome = true,
                            Name = "Macbook sticker",
                            ParentId = 1,
                            SeoAlias = "macbook-sticker",
                            SeoDescription = "Sticker for Macbook",
                            SeoTitle = "Macbook sticker",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7010),
                            IsShowOnHome = true,
                            Name = "Usb-c Hub",
                            ParentId = 1,
                            SeoAlias = "usb-c-hub",
                            SeoDescription = "Usb-c Hub",
                            SeoTitle = "Usb-c Hub",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7010),
                            IsShowOnHome = true,
                            Name = "Iphone Charging Cable",
                            ParentId = 2,
                            SeoAlias = "iphone-charging-cable",
                            SeoDescription = "The charging cable for Iphone",
                            SeoTitle = "Iphone Charging Cable",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7010),
                            IsShowOnHome = true,
                            Name = "Iphone Stand",
                            ParentId = 2,
                            SeoAlias = "iphone-stand",
                            SeoDescription = "Stand for Iphone",
                            SeoTitle = "Iphone Stand",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7060),
                            IsShowOnHome = true,
                            Name = "Ipad Case",
                            ParentId = 3,
                            SeoAlias = "ipad-case",
                            SeoDescription = "Case for Ipad",
                            SeoTitle = "Ipad Case",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7060),
                            IsShowOnHome = true,
                            Name = "Ipad Tempered Glass",
                            ParentId = 3,
                            SeoAlias = "ipad-tempered-glass",
                            SeoDescription = "Tempered glass for Ipad",
                            SeoTitle = "Ipad Tempered Glass",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7060),
                            IsShowOnHome = true,
                            Name = "Ipad Stand",
                            ParentId = 3,
                            SeoAlias = "ipad-stand",
                            SeoDescription = "Stand for Ipad",
                            SeoTitle = "Ipad Stand",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7060),
                            IsShowOnHome = true,
                            Name = "Mechanical Keyboard",
                            ParentId = 4,
                            SeoAlias = "mechanical-keyboard",
                            SeoDescription = "Mechanical Keyboard",
                            SeoTitle = "Mechanical Keyboard",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7060),
                            IsShowOnHome = true,
                            Name = "Mechanical Mouse",
                            ParentId = 4,
                            SeoAlias = "mechanical-mouse",
                            SeoDescription = "Mechanical Mouse",
                            SeoTitle = "Mechanical Mouse",
                            SortOrder = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7060),
                            IsShowOnHome = true,
                            Name = "Macbook Cleaning Kit",
                            ParentId = 1,
                            SeoAlias = "macbook-cleaning-kit",
                            SeoDescription = "Macbook Cleaning Kit",
                            SeoTitle = "Macbook Cleaning Kit",
                            SortOrder = 0,
                            Status = 1
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ApplyAll")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LimitedOrderPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("Discounts", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShipEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShipPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DecreasedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SeoAlias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 7,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7090),
                            DecreasedPrice = 0m,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsFeatured = true,
                            Name = "JCPAL 5in1 Premium Cleaning Set For Macbook, Laptop, Phone, Camera",
                            OriginalPrice = 180000m,
                            Price = 200000m,
                            SeoAlias = "jcpal-5in1-premium-cleaning-set-for-macbook-laptop-phone-camera",
                            SeoDescription = "JCPAL 5in1 Premium Cleaning Set For Macbook, Laptop, Phone, Camera",
                            SeoTitle = "JCPAL 5in1 Premium Cleaning Set For Macbook, Laptop, Phone, Camera",
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 6,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7090),
                            DecreasedPrice = 0m,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsFeatured = true,
                            Name = "Hyperdrive Dual 4K HDMI 10in1 USB-C Hub/Port (2 monitors) Macbook M1",
                            OriginalPrice = 180000m,
                            Price = 200000m,
                            SeoAlias = "hyperdrive-dual-4k-hdmi-10in1-usbc-hubport-2-monitors-macbook-m1",
                            SeoDescription = "Hyperdrive Dual 4K HDMI 10in1 USB-C Hub/Port (2 monitors) Macbook M1",
                            SeoTitle = "Hyperdrive Dual 4K HDMI 10in1 USB-C Hub/Port (2 monitors) Macbook M1",
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7100),
                            DecreasedPrice = 0m,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsFeatured = true,
                            Name = "Andora 6in1 Macbook Stickers For Macbook Pro 16 inch 2021",
                            OriginalPrice = 600000m,
                            Price = 650000m,
                            SeoAlias = "andora-6in1-macbook-stickers-for-macbook-pro-16-inch-2021",
                            SeoDescription = "Andora 6in1 Macbook Stickers For Macbook Pro 16 inch 2021",
                            SeoTitle = "Andora 6in1 Macbook Stickers For Macbook Pro 16 inch 2021",
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7100),
                            DecreasedPrice = 0m,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsFeatured = true,
                            Name = "Apple 20W USB Type-C Charger",
                            OriginalPrice = 650000m,
                            Price = 700000m,
                            SeoAlias = "apple-20w-usb-typec-charger",
                            SeoDescription = "Apple 20W USB Type-C Charger",
                            SeoTitle = "Apple 20W USB Type-C Charger",
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 15,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7100),
                            DecreasedPrice = 0m,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsFeatured = true,
                            Name = "Stand/Aluminum Elevator Stand for iPhone, iPad, Phone with Adjustable Tilt Angle WIWU",
                            OriginalPrice = 210000m,
                            Price = 250000m,
                            SeoAlias = "standaluminum-elevator-stand-for-iphone-ipad-phone-with-adjustable-tilt-angle-wiwu",
                            SeoDescription = "Stand/Aluminum Elevator Stand for iPhone, iPad, Phone with Adjustable Tilt Angle WIWU",
                            SeoTitle = "Stand/Aluminum Elevator Stand for iPhone, iPad, Phone with Adjustable Tilt Angle WIWU",
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 15,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7100),
                            DecreasedPrice = 0m,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsFeatured = true,
                            Name = "WIWU Waltz Rotating Keyboard Case / Bluetooth Keyboard With Tracpad 360 Degree Rotating Screen WIWU Waltz Rotating Keyboard For iPad Pro 11 inch 2018-2021, Air 4 and iPad Gen 7/8/9",
                            OriginalPrice = 1100000m,
                            Price = 1300000m,
                            SeoAlias = "hwiwu-waltz-rotating-keyboard-case--bluetooth-keyboard-with-tracpad-360-degree-rotating-screen-wiwu-waltz-rotating-keyboard-for-ipad-pro-11-inch-20182021-air-4-and-ipad-gen-789",
                            SeoDescription = "WIWU Waltz Rotating Keyboard Case / Bluetooth Keyboard With Tracpad 360 Degree Rotating Screen WIWU Waltz Rotating Keyboard For iPad Pro 11 inch 2018-2021, Air 4 and iPad Gen 7/8/9",
                            SeoTitle = "WIWU Waltz Rotating Keyboard Case / Bluetooth Keyboard With Tracpad 360 Degree Rotating Screen WIWU Waltz Rotating Keyboard For iPad Pro 11 inch 2018-2021, Air 4 and iPad Gen 7/8/9",
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 7,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7100),
                            DecreasedPrice = 0m,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsFeatured = true,
                            Name = "9H Anti-Scratch, Anti-Shock, Anti-Fingerprint Tempered Glass For All iPad JCPAL iClara (iPad Pro 11', Pro 12'9, Air 1/2/3/4, Mini 6, Gen 2/3/4/ 5/6/7/8/9)",
                            OriginalPrice = 300000m,
                            Price = 350000m,
                            SeoAlias = "9h-antiscratch-antishock-antifingerprint-tempered-glass-for-all-ipad-jcpal-iclara-ipad-pro-11-pro-129-air-1234-mini-6-gen-234-56789",
                            SeoDescription = "9H Anti-Scratch, Anti-Shock, Anti-Fingerprint Tempered Glass For All iPad JCPAL iClara (iPad Pro 11', Pro 12'9, Air 1/2/3/4, Mini 6, Gen 2/3/4/ 5/6/7/8/9)",
                            SeoTitle = "9H Anti-Scratch, Anti-Shock, Anti-Fingerprint Tempered Glass For All iPad JCPAL iClara (iPad Pro 11', Pro 12'9, Air 1/2/3/4, Mini 6, Gen 2/3/4/ 5/6/7/8/9)",
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 8,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7110),
                            DecreasedPrice = 0m,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsFeatured = true,
                            Name = "KEYCHRON K6 Mechanical Keyboard Aluminum – No LED – HOTSWAP",
                            OriginalPrice = 16000000m,
                            Price = 1890000m,
                            SeoAlias = "keychron-k6-mechanical-keyboard-aluminum-–-no-led-–-hotswap",
                            SeoDescription = "KEYCHRON K6 Mechanical Keyboard Aluminum – No LED – HOTSWAP",
                            SeoTitle = "KEYCHRON K6 Mechanical Keyboard Aluminum – No LED – HOTSWAP",
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 9,
                            DateCreated = new DateTime(2022, 3, 3, 21, 47, 18, 258, DateTimeKind.Local).AddTicks(7110),
                            DecreasedPrice = 0m,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Details = "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                            IsFeatured = true,
                            Name = "LOFREE Maus Blue Pearl Bluetooth Mouse",
                            OriginalPrice = 1200000m,
                            Price = 1500000m,
                            SeoAlias = "lofree-maus-blue-pearl-bluetooth-mouse",
                            SeoDescription = "LOFREE Maus Blue Pearl Bluetooth Mouse",
                            SeoTitle = "LOFREE Maus Blue Pearl Bluetooth Mouse",
                            Stock = 10,
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 14
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 8
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 11
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 12
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 13
                        });
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Rating", b =>
                {
                    b.Property<int>("RateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RateId"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<int>("RatePoint")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RateId");

                    b.HasIndex("ProductId");

                    b.ToTable("Ratings", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Slides", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("cf517a65-75d0-480c-9566-601b1e607d25"),
                            RoleId = new Guid("725efe2e-a534-40c4-ab0d-20c947e6c0eb")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserToken", (string)null);
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Cart", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Backend.Models.AppUser", "AppUser")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Discount", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Backend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Order", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.OrderDetail", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Backend.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Product", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductCategory", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Backend.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.ProductImage", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Rating", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.Product", "Product")
                        .WithMany("ProductRatings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Transaction", b =>
                {
                    b.HasOne("eCommerce.Backend.Models.AppUser", "AppUser")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.AppUser", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("eCommerce.Backend.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
